"""core star schema

Revision ID: 0001
Revises:
Create Date: 2026-06-22 18:59:36.784197
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_commodity',
    sa.Column('commodity_key', sa.Integer(), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('commodity_name', sa.String(length=120), nullable=False),
    sa.Column('commodity_group', sa.Enum('agriculture', 'energy', 'metal', 'logistics', name='commoditygroup', native_enum=False, length=20), nullable=False),
    sa.Column('base_unit', sa.String(length=40), nullable=False),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('commodity_key'),
    sa.UniqueConstraint('commodity_code')
    )
    op.create_table('dim_data_source',
    sa.Column('data_source_key', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('access', sa.String(length=40), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('data_source_key'),
    sa.UniqueConstraint('source_code')
    )
    op.create_table('dim_region',
    sa.Column('region_key', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=60), nullable=False),
    sa.Column('region_name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('region_key'),
    sa.UniqueConstraint('region_code')
    )
    op.create_table('commodity_profile_registry',
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('source_path', sa.String(length=300), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registry_id'),
    sa.UniqueConstraint('commodity_code'),
    sa.UniqueConstraint('commodity_key')
    )
    op.create_table('commodity_region_map',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=False),
    sa.Column('region_key', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('production', 'consumption', 'export', 'import', 'weather', name='regionrole', native_enum=False, length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_key'], ['dim_region.region_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id'),
    sa.UniqueConstraint('commodity_key', 'region_key', 'role', name='uq_commodity_region_map')
    )
    op.create_table('dim_market_instrument',
    sa.Column('market_instrument_key', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=False),
    sa.Column('instrument_code', sa.String(length=60), nullable=False),
    sa.Column('exchange', sa.String(length=120), nullable=True),
    sa.Column('symbol', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_unit', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_instrument_key'),
    sa.UniqueConstraint('commodity_key', 'instrument_code', name='uq_dim_market_instrument_commodity_code')
    )
    op.create_table('fact_event_risk',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=True),
    sa.Column('region_key', sa.Integer(), nullable=True),
    sa.Column('data_source_key', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('metric_code', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('release_date >= event_date', name='ck_fact_event_risk_release'),
    sa.CheckConstraint('revision >= 0', name='ck_fact_event_risk_revision'),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_key'], ['dim_data_source.data_source_key'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_key'], ['dim_region.region_key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('fact_event_risk', schema=None) as batch_op:
        batch_op.create_index('ix_fact_event_risk_release_date', ['release_date'], unique=False)

    op.create_table('fact_logistics_periodic',
    sa.Column('logistics_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=True),
    sa.Column('region_key', sa.Integer(), nullable=True),
    sa.Column('data_source_key', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('indicator_code', sa.String(length=80), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_fact_logistics_period'),
    sa.CheckConstraint('release_date >= period_end', name='ck_fact_logistics_release'),
    sa.CheckConstraint('revision >= 0', name='ck_fact_logistics_revision'),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_key'], ['dim_data_source.data_source_key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_key'], ['dim_region.region_key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('logistics_id')
    )
    with op.batch_alter_table('fact_logistics_periodic', schema=None) as batch_op:
        batch_op.create_index('ix_fact_logistics_periodic_release_date', ['release_date'], unique=False)

    op.create_table('fact_macro_daily',
    sa.Column('macro_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=True),
    sa.Column('data_source_key', sa.Integer(), nullable=True),
    sa.Column('macro_date', sa.Date(), nullable=False),
    sa.Column('indicator_code', sa.String(length=80), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('release_date >= macro_date', name='ck_fact_macro_daily_release'),
    sa.CheckConstraint('revision >= 0', name='ck_fact_macro_daily_revision'),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_key'], ['dim_data_source.data_source_key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('macro_id')
    )
    with op.batch_alter_table('fact_macro_daily', schema=None) as batch_op:
        batch_op.create_index('ix_fact_macro_daily_release_date', ['release_date'], unique=False)

    op.create_table('fact_supply_demand_periodic',
    sa.Column('sd_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=False),
    sa.Column('region_key', sa.Integer(), nullable=True),
    sa.Column('data_source_key', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric_code', sa.String(length=80), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_fact_sd_period'),
    sa.CheckConstraint('release_date >= period_end', name='ck_fact_sd_release'),
    sa.CheckConstraint('revision >= 0', name='ck_fact_sd_revision'),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_key'], ['dim_data_source.data_source_key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_key'], ['dim_region.region_key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sd_id')
    )
    with op.batch_alter_table('fact_supply_demand_periodic', schema=None) as batch_op:
        batch_op.create_index('ix_fact_supply_demand_periodic_release_date', ['release_date'], unique=False)

    op.create_table('fact_weather_daily',
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=False),
    sa.Column('region_key', sa.Integer(), nullable=False),
    sa.Column('data_source_key', sa.Integer(), nullable=True),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('metric_code', sa.String(length=60), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('release_date >= weather_date', name='ck_fact_weather_daily_release'),
    sa.CheckConstraint('revision >= 0', name='ck_fact_weather_daily_revision'),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_key'], ['dim_data_source.data_source_key'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_key'], ['dim_region.region_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('weather_id')
    )
    with op.batch_alter_table('fact_weather_daily', schema=None) as batch_op:
        batch_op.create_index('ix_fact_weather_daily_release_date', ['release_date'], unique=False)
        batch_op.create_index('uq_fact_weather_daily_grain', ['commodity_key', 'region_key', 'metric_code', 'weather_date', 'revision'], unique=True)

    op.create_table('fact_price_daily',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('commodity_key', sa.Integer(), nullable=False),
    sa.Column('market_instrument_key', sa.Integer(), nullable=True),
    sa.Column('data_source_key', sa.Integer(), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('settle', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('open_interest', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('release_date >= price_date', name='ck_fact_price_daily_release'),
    sa.CheckConstraint('revision >= 0', name='ck_fact_price_daily_revision'),
    sa.ForeignKeyConstraint(['commodity_key'], ['dim_commodity.commodity_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_key'], ['dim_data_source.data_source_key'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_instrument_key'], ['dim_market_instrument.market_instrument_key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('price_id')
    )
    with op.batch_alter_table('fact_price_daily', schema=None) as batch_op:
        batch_op.create_index('ix_fact_price_daily_release_date', ['release_date'], unique=False)

    # ### end Alembic commands ###

    # NULL-safe grain uniqueness for fact tables with nullable keys (autogenerate
    # skips expression indexes). Periodic facts key on the explicit period range.
    op.create_index(
        "uq_fact_price_daily_grain", "fact_price_daily",
        [sa.text("commodity_key"), sa.text("coalesce(market_instrument_key, -1)"),
         sa.text("price_date"), sa.text("revision")], unique=True,
    )
    op.create_index(
        "uq_fact_macro_daily_grain", "fact_macro_daily",
        [sa.text("coalesce(commodity_key, -1)"), sa.text("indicator_code"),
         sa.text("macro_date"), sa.text("revision")], unique=True,
    )
    op.create_index(
        "uq_fact_logistics_grain", "fact_logistics_periodic",
        [sa.text("coalesce(commodity_key, -1)"), sa.text("coalesce(region_key, -1)"),
         sa.text("data_source_key"), sa.text("indicator_code"),
         sa.text("period_start"), sa.text("period_end"),
         sa.text("release_date"), sa.text("revision")], unique=True,
    )
    op.create_index(
        "uq_fact_sd_grain", "fact_supply_demand_periodic",
        [sa.text("commodity_key"), sa.text("coalesce(region_key, -1)"),
         sa.text("data_source_key"), sa.text("metric_code"),
         sa.text("period_start"), sa.text("period_end"),
         sa.text("release_date"), sa.text("revision")], unique=True,
    )
    op.create_index(
        "uq_fact_event_risk_grain", "fact_event_risk",
        [sa.text("coalesce(commodity_key, -1)"), sa.text("coalesce(region_key, -1)"),
         sa.text("metric_code"), sa.text("event_date"), sa.text("revision")], unique=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_fact_event_risk_grain", table_name="fact_event_risk")
    op.drop_index("uq_fact_sd_grain", table_name="fact_supply_demand_periodic")
    op.drop_index("uq_fact_logistics_grain", table_name="fact_logistics_periodic")
    op.drop_index("uq_fact_macro_daily_grain", table_name="fact_macro_daily")
    op.drop_index("uq_fact_price_daily_grain", table_name="fact_price_daily")
    with op.batch_alter_table('fact_price_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_price_daily_release_date')

    op.drop_table('fact_price_daily')
    with op.batch_alter_table('fact_weather_daily', schema=None) as batch_op:
        batch_op.drop_index('uq_fact_weather_daily_grain')
        batch_op.drop_index('ix_fact_weather_daily_release_date')

    op.drop_table('fact_weather_daily')
    with op.batch_alter_table('fact_supply_demand_periodic', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_supply_demand_periodic_release_date')

    op.drop_table('fact_supply_demand_periodic')
    with op.batch_alter_table('fact_macro_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_macro_daily_release_date')

    op.drop_table('fact_macro_daily')
    with op.batch_alter_table('fact_logistics_periodic', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_logistics_periodic_release_date')

    op.drop_table('fact_logistics_periodic')
    with op.batch_alter_table('fact_event_risk', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_event_risk_release_date')

    op.drop_table('fact_event_risk')
    op.drop_table('dim_market_instrument')
    op.drop_table('commodity_region_map')
    op.drop_table('commodity_profile_registry')
    op.drop_table('dim_region')
    op.drop_table('dim_data_source')
    op.drop_table('dim_commodity')
    # ### end Alembic commands ###
