"""add source provenance columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-23 04:05:41.636729
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_event_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_record_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_payload_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('fact_logistics_periodic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_record_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_payload_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('fact_macro_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_record_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_payload_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('fact_price_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_record_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_payload_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('fact_supply_demand_periodic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_record_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_payload_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('fact_weather_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_record_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_payload_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_weather_daily', schema=None) as batch_op:
        batch_op.drop_column('source_payload_hash')
        batch_op.drop_column('source_record_id')

    with op.batch_alter_table('fact_supply_demand_periodic', schema=None) as batch_op:
        batch_op.drop_column('source_payload_hash')
        batch_op.drop_column('source_record_id')

    with op.batch_alter_table('fact_price_daily', schema=None) as batch_op:
        batch_op.drop_column('source_payload_hash')
        batch_op.drop_column('source_record_id')

    with op.batch_alter_table('fact_macro_daily', schema=None) as batch_op:
        batch_op.drop_column('source_payload_hash')
        batch_op.drop_column('source_record_id')

    with op.batch_alter_table('fact_logistics_periodic', schema=None) as batch_op:
        batch_op.drop_column('source_payload_hash')
        batch_op.drop_column('source_record_id')

    with op.batch_alter_table('fact_event_risk', schema=None) as batch_op:
        batch_op.drop_column('source_payload_hash')
        batch_op.drop_column('source_record_id')

    # ### end Alembic commands ###
