#!/usr/bin/env python3
"""
Phase 5B: Materialized View Compiler
Reads commodity YAML profiles and generates a deterministic SQL script for
a wide Materialized View (mv_ml_daily_features_wide).
"""

import re
import sys
from pathlib import Path

import yaml


def sanitize_identifier(name: str) -> str:
    """Ensures metric code is a valid SQL identifier (prevents injection)."""
    # Only allow alphanumeric and underscore
    if not re.match(r"^[a-zA-Z0-9_]+$", name):
        raise ValueError(f"Invalid metric code (potential SQL injection): {name}")
    return name.lower()


def metric_extract_sql(metric_code: str) -> str:
    """Extract one scalar metric from the JSONB array.

    Safe because v_ml_daily_feature_scalar guarantees at most one event per
    (as_of_date, commodity_key, metric_code) before jsonb_agg.
    """
    return (
        f"(jsonb_path_query_first(features_jsonb, "
        f"'$[*] ? (@.metric_code == \"{metric_code}\").metric_value_numeric'))"
        f"::numeric"
    )


def main():
    project_root = Path(__file__).parent.parent.parent
    config_dir = project_root / "configs" / "commodities"

    if not config_dir.exists():
        print(f"Config directory {config_dir} does not exist.", file=sys.stderr)
        raise SystemExit(1)

    # Using a set to guarantee unique columns across all commodities
    metrics = set()

    # Always include baseline price
    metrics.add("price_close")

    driver_groups = [
        "physical_drivers",
        "macro_drivers",
        "logistics_drivers",
        "event_risk_drivers",
    ]

    for yaml_file in config_dir.glob("*.yaml"):
        with open(yaml_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)

        if not data:
            continue

        for group in driver_groups:
            if group in data and isinstance(data[group], list):
                for item in data[group]:
                    if "metric_code" in item:
                        metrics.add(sanitize_identifier(item["metric_code"]))

    # Sort deterministically
    sorted_metrics = sorted(list(metrics))

    # Generate SQL
    sql_lines = [
        "-- ============================================================================",
        "-- 010_mv_ml_daily_features_wide.sql",
        "-- Phase 5B: Generated Wide Materialized View for ML",
        "-- DO NOT EDIT DIRECTLY. Generated by compile_ml_feature_views.py",
        "-- Scalar grain: one value per (as_of_date, commodity_key, metric_code)",
        "-- via v_ml_daily_feature_scalar before jsonb_agg.",
        "-- ============================================================================",
        "",
        "CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ml_daily_features_wide AS",
        "SELECT",
        "    as_of_date,",
        "    commodity_key,",
    ]

    for i, m in enumerate(sorted_metrics):
        comma = "," if i < len(sorted_metrics) - 1 else ""
        line = f"    {metric_extract_sql(m)} AS {m}{comma}"
        sql_lines.append(line)

    sql_lines.append("FROM v_ml_daily_features_jsonb")
    sql_lines.append("WITH NO DATA;")

    # Write to output file
    out_dir = project_root / "db" / "views" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "010_mv_ml_daily_features_wide.sql"

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines) + "\n")

    print(
        f"Generated wide view SQL with {len(sorted_metrics)} metrics to "
        f"{out_path.relative_to(project_root)}"
    )


if __name__ == "__main__":
    main()